- hosts: dev
  become: true
  remote_user: vagrant
  vars:
    - pack: "httpd"


  tasks:
  
    -  name: installing apache
       yum:
         name: "{{ pack }}"
         state: "installed"
  
    -  name: creating index.html
       copy:
         src: index.html
         dest: /var/www/html/index.html
       notify: service

    -  name: service start
       service:
         name: "{{ pack }}"
         state: "started"


  handlers:
    -  name: service
       service:
         name: "{{ pack }}"
         state: "restarted"

           
 
  
