---
# tasks file for sharath

- name: "install {{ item }}"
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "{{ pack }}"

- name: Copying the apache conf file
  template:
    src: "{{ item.srcf }}"
    dest: "{{ item.destf }}"
  notify: apache
  with_items:
    - "{{ files }}"


- name: service start
  service:
    name: "{{ pack[0] }}"
    state: "started"
